// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxRMeqYVuTvkjMR_BFMPw0W8BoD0ZErUY',
    appId: '1:830099740011:web:e341439faeceb7176aa82e',
    messagingSenderId: '830099740011',
    projectId: 'cooking-champs-79749',
    authDomain: 'cooking-champs-79749.firebaseapp.com',
    storageBucket: 'cooking-champs-79749.firebasestorage.app',
    measurementId: 'G-XMRR3BRJ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLF7KnSvl0OyHhpVUF9LSOyYwP1sOFr08',
    appId: '1:830099740011:android:99d94e0769a9bd4b6aa82e',
    messagingSenderId: '830099740011',
    projectId: 'cooking-champs-79749',
    storageBucket: 'cooking-champs-79749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoJ0dgM3iqQC-xchHtMii9XKD35eM6m2I',
    appId: '1:830099740011:ios:f549afdf4c6212a86aa82e',
    messagingSenderId: '830099740011',
    projectId: 'cooking-champs-79749',
    storageBucket: 'cooking-champs-79749.firebasestorage.app',
    iosBundleId: 'com.cc.cookingchamps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoJ0dgM3iqQC-xchHtMii9XKD35eM6m2I',
    appId: '1:830099740011:ios:f549afdf4c6212a86aa82e',
    messagingSenderId: '830099740011',
    projectId: 'cooking-champs-79749',
    storageBucket: 'cooking-champs-79749.firebasestorage.app',
    iosBundleId: 'com.cc.cookingchamps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxRMeqYVuTvkjMR_BFMPw0W8BoD0ZErUY',
    appId: '1:830099740011:web:20f3261a4fc0453b6aa82e',
    messagingSenderId: '830099740011',
    projectId: 'cooking-champs-79749',
    authDomain: 'cooking-champs-79749.firebaseapp.com',
    storageBucket: 'cooking-champs-79749.firebasestorage.app',
    measurementId: 'G-JY1QC8TLTP',
  );
}
